[project]
name = "workstation-cdk"
version = "0.1.0"
description = "AWS CDK infrastructure for EC2 workstation provisioning system"
requires-python = ">=3.13"
dependencies = [
    "aws-cdk-lib==2.152.0",
    "constructs>=10.0.0,<11.0.0",
]
